xa=0;ya=100;vax=0;vay=0;aax=0;aay=0;lab=100;phia=1*2*pi/360;omga=5;epsa=0;
xd=200;yd=0;vdx=0;vdy=0;adx=0;ady=0;lbc=200;ldc=200;lde=100.24;
xp=200;yp=0;vpx=0;vpy=0;apx=0;apy=0;lef=200;phi5=0;omg5=0;eps5=0;
while(phia<=2*pi)
[xb,yb,vbx,vby,abx,aby]=dangan(xa,ya,vax,vay,aax,aay,lab,phia,omga,epsa);
[xc,yc,vcx,vcy,acx,acy,phi2,phi3,omg2,omg3,eps2,eps3]=RRRshuanggan(xb,yb,vbx,vby,abx,aby,xd,yd,vdx,vdy,adx,ady,lbc,ldc,1);
[xe,ye,vex,vey,aex,aey]=dangan(xd,yd,vdx,vdy,adx,ady,lde,phi3,omg3,eps3);
[xf,yf,vfx,vfy,afx,afy,sr,vr,ar,phi4,omg4,eps4]=RRPshuanggan(xe,ye,vex,vey,aex,aey,xp,yp,vpx,vpy,apx,apy,lef,phi5,omg5,eps5,1);
subplot(321);
plot(phia*360/(2*pi),phi3*360/(2*pi),'*','LineWidth',1);
xlabel('杆1角位移\phi_1/(\circ)'); 
ylabel('杆3角位移\phi_3/(\circ)'); 
title('杆3角位移曲线图');
hold on;
subplot(323);
plot(phia*360/(2*pi),omg3/(2*pi),'*','LineWidth',1);
xlabel('杆1角位移\phi_1/(\circ)'); 
ylabel('杆3角速度\phi_3/(rad/s)'); 
title('杆3角速度曲线图');
hold on;
subplot(325);
plot(phia*360/(2*pi),eps3/(2*pi),'*','LineWidth',1);
xlabel('杆1角位移\phi_1/(\circ)'); 
ylabel('杆3角加速度\phi_3/(rad/s^2)'); 
title('杆3角加速度曲线图');
hold on;
subplot(322);
plot(phia*360/(2*pi),xf,'*','LineWidth',1);
xlabel('杆1角位移\phi_1/(\circ)'); 
ylabel('F位移/mm'); 
title('F位移曲线图');
hold on;
subplot(324);
plot(phia*360/(2*pi),vfx,'*','LineWidth',1);
xlabel('杆1角位移\phi_1/(\circ)'); 
ylabel('F速度/（mm/s）'); 
title('F速度曲线图');
hold on;
subplot(326);
plot(phia*360/(2*pi),afx,'*','LineWidth',1);
xlabel('杆1角位移\phi_1/(\circ)'); 
ylabel('F加速度/（mm/s^2）'); 
title('F加速度曲线图');
hold on;
phia=phia+1*2*pi/360;
end;
hold off;



